Second Saml Login Option
KoALa-MHF/koala-app pull request #456
Opened 2023-12-06 19:03 UTC by TS-Daniel16

2023-12-06 22:16 UTC, TS-Tino16 requested changes

2023-12-06 22:16 UTC, TS-Tino16 commented on apps/api/src/app/auth/auth.controller.ts
> +  @UseGuards(SamlAuthOptionGuard)
is it required to have two different guards for that? they look the same for me

2023-12-06 22:16 UTC, TS-Tino16 commented on apps/api/src/app/core/guards/saml-auth-option.guard.ts
> +export class SamlAuthOptionGuard extends AuthGuard('samlOption') {}
do we need a second one?

2023-12-06 22:20 UTC, TS-Tino16 approved these changes

2023-12-07 07:14 UTC, TS-Daniel16 commented
#449

2023-12-07 07:28 UTC, merged