adds audio/comments icon to annotations
KoALa-MHF/koala-app pull request #478
Opened 2023-12-21 01:15 UTC by TS-Stefan

also fixes annotation delete buttons hide issue.

2023-12-23 20:25 UTC, TS-Daniel16 commented
@TS-Stefan is this ready for review or are you working on it?

2024-01-02 23:35 UTC, TS-Stefan commented
I am done

2024-01-07 15:23 UTC, TS-Daniel16 requested changes

2024-01-07 15:23 UTC, TS-Daniel16 commented on apps/koala-frontend/src/app/features/sessions/components/annotation/annotation.component.html
> +    [ngStyle]="{ visibility: !displayMode && enableAnnotationDelete ? 'visibile' : 'hidden' }"
there is a type in visible (visibile)

2024-01-07 15:23 UTC, TS-Daniel16 commented on apps/koala-frontend/src/app/features/sessions/components/annotation/annotation.component.html
> +          [ngStyle]="{ visibility: marker.visible ? 'visibile' : 'hidden' }"
Same as in line 5

2024-01-15 20:57 UTC, TS-Tino16 approved these changes
LGTM

2024-01-19 12:10 UTC, TS-Daniel16 approved these changes

2024-01-19 12:10 UTC, merged