adds sound controls, soundwave and skeleton session page
KoALa-MHF/koala-app pull request #77
Opened 2023-01-22 20:35 UTC by TS-Stefan

2023-01-28 16:02 UTC, TS-Daniel16 requested changes

2023-01-28 16:02 UTC, TS-Daniel16 commented on apps/koala-frontend/src/app/features/sessions/pages/session/session.page.ts
> +          summary: 'Kein Audio File gefunden',
Could you make these texts translatable

2023-01-28 16:02 UTC, TS-Daniel16 commented on apps/koala-frontend/src/app/features/sessions/pages/session/session.page.spec.ts
> +describe('SessionCreateComponent', () => {
I guess we should this file as we did for the other components as long as we do not want to add component tests (which I cannot see here at the moment)

2023-01-28 16:02 UTC, TS-Daniel16 commented on apps/koala-frontend/src/app/features/sessions/pages/session/session.page.html
> +    <p-tabPanel header="Auswertung"> </p-tabPanel>
make header translatable

2023-01-28 16:02 UTC, TS-Daniel16 commented on apps/koala-frontend/src/app/features/sessions/components/audio-player/audio-player.component.html
> +<div [id]="mc.uuid"></div>
What are these used for?

2023-02-06 21:27 UTC, TS-Stefan commented on apps/koala-frontend/src/app/features/sessions/services/media-control.service.ts
> +      audio.src = URL.createObjectURL(audioBlob);
I am throwing an error in the catch. So it should jump out of the `load` function.

2023-02-07 13:06 UTC, TS-Stefan commented on apps/koala-frontend/src/app/features/sessions/components/audio-player/audio-player.component.html
> +<div [id]="mc.uuid"></div>
removed

2023-02-07 14:18 UTC, merged